spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/arosaje
    username: nosithouss
    password: nosithouss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:migrations
  security:
    user:
      name: nosithouss
      password: nosithouss

debug: true

logging:
  level:
    web: DEBUG

upload:
  path: "here"
