spring:
  main:
    web-application-type: servlet
    etl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/arosaje
    username: nosithouss
    password: nosithouss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: true
    baselineOnMigrate: true
    locations: classpath:migrations
  security:
    user:
      name: nosithouss
      password: nosithouss

debug: false

logging:
  level:
    web: DEBUG

#upload:
#  path: "uploads"
#
#apache:
#  url: "http://localhost:80"
#  uploadUrl: "http://localhost:80/assets"