spring:
  profiles:
    active: default
  main:
    web-application-type: servlet
    etl: true
  datasource:
    url: jdbc:postgresql://localhost/arosaje
    username: nosithouss
    password: nosithouss
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
    baselineOnMigrate: true
    locations: classpath:migrations
  security:
    user:
      name: nosithouss
      password: nosithouss

springdoc:
  swagger-ui:
    path=/swagger-ui.html

debug: false

logging:
  level:
    web: DEBUG