spring:
  profiles:
    active: dev
  main:
    web-application-type: servlet
    etl: true
  datasource:
    url: jdbc:postgresql://localhost/arosaje
    username: nosithouss
    password: nosithouss