spring:
  profiles:
    active: default
  config:
    import: optional:file:.env[.properties]
  main:
    web-application-type: servlet
    etl: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PWD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:migrations
  security:
    user:
      name: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PWD}
    encryption:
      key: ${SPRING_SECURITY_ENCRYPTION_KEY}

debug: false

logging:
  level:
    web: DEBUG

etl:
  first-plant-page: "/api/v1/plants?page=1"